### ISSUE TITLE
Phone app thinks watch app is not installed when it is

### ISSUE THREAD

**Issue by TodBonzalez** [matejdro/WearVibrationCenter#12]
Hi!

I would love to get this to work to replace Feel the Wear. However, when I sideload the app via ADB to my GalaxyWatch4, while it appears in the watch's app list the phone app still says it is not present on the watch. What can I try?

Thanks!

**Comment by TodBonzalez** [comment]
![Screenshot_20230416_155302_wearvibrationcenter](https://user-images.githubusercontent.com/9299021/232347476-65c06b6e-2d04-4ac2-884f-e6693800fee0.png)

Here you can see the app is installed on the watch, but the watch thinks it is a phone.

**Comment by matejdro** [comment]
Under release, there are two apks, wear and mobile: https://github.com/matejdro/WearVibrationCenter/releases/tag/1.3.0

You need to install wear apk to the watch and mobile one to the phone

**Comment by TodBonzalez** [comment]
Solved, thanks!
