### ISSUE TITLE
How to make calls vibrate?

### ISSUE THREAD

**Issue by TodBonzalez** [matejdro/WearVibrationCenter#13]
I tried to add vibrations to the Phone app, but that only affected notifications for missed calls. Is there a way to either make vibrations for a call, or else let through the regular notification when someone calls?

**Comment by TodBonzalez** [comment]
For what it's worth, if I turn on vibrations for my GalaxyWear app, it works normally. However, I'd like to silence this and control it through Vibration Center.

**Comment by matejdro** [comment]
You can't really. App only works for regular notifications.

**Comment by TodBonzalez** [comment]
I see. So, what do folks do typically? Just have no incoming call notifications?

**Comment by TodBonzalez** [comment]
Feel the Wear does have a separate call function, for what it's worth. I wonder if that feature could be replicated.

**Comment by matejdro** [comment]
I guess it depends on the watch? My GW4 shows call notifications natively.

**Comment by TodBonzalez** [comment]
I have a GW4. What settings do you use? I want the watch to buzz for calls, and the phone to stay silent, and I want to avoid duplicate vibration notifications. Right now, I can only seem to get it to work with duplicate vibrations.

**Comment by matejdro** [comment]
I think enabling Settings -> Advanced features -> Remote connection (in the Galaxy Wear phone app) does the trick.

**Comment by TodBonzalez** [comment]
hmm, I have that enabled already, so I don't think that's it
